/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData filter = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next_forward = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_button = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next_back = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
